version: '3.1'

services:

  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pg123
      POSTGRES_USER: liya
      POSTGRES_DB: events
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./data_db:/var/lib/postgresql/data
    ports:
      - "5444:5432"